# SPDX-License-Identifier: MPL-2.0
# Dependabot configuration — adopts the corrected RSR template approach
# (open-pull-requests-limit: 10 on cargo, grouped minor/patch).

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      cargo:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
